vich_uploader:
    db_driver: orm

    mappings:
       photo_media:
           uri_prefix: /media/photo
           upload_destination: '%photo_uploads%'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
