vich_uploader:
    db_driver: orm
    storage: flysystem
    mappings:
       photo_media:
           uri_prefix: /media/photo
           # upload_destination: dropbox_filesystem
           upload_destination: local_filesystem
           namer: Vich\UploaderBundle\Naming\UniqidNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
