vich_uploader:
    db_driver: orm

    mappings:
       avatars:
           uri_prefix: /api/media/avatars
           upload_destination: '%avatar_uploads%'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
