vich_uploader:
    db_driver: orm

    mappings:
       photo_media:
           uri_prefix: /media/photo
           upload_destination: '%photo_uploads%'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
